name: Next.js Build and S3 Upload

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install project dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Upload to S3
        uses: aws-actions/aws-s3-deploy@v2
        with:
          args: --acl public-read --follow-symlinks --delete
          bucket: gitaction-sheltonchin
          exclude: '*.html'
          include: '**/*'
          local-dir: out/
          overwrite: true
