name: Deploy to AWS S3

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-southeast-2
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET_NAME: sheltonchin-gohusky

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
      
    - name: Build app
      run: npm run build
      
    - name: Upload to S3
      uses: aws-actions/aws-s3-deploy@v2
      with:
        args: --acl public-read --follow-symlinks --delete
        bucket: sheltonchin-gohusky
        exclude: '*.html'
        include: '**/*'
        local-dir: out/
        overwrite: true
    
